### ISSUE TITLE
Error when trying to join a team

### ISSUE THREAD

**Issue by HZooly** [jwngr/tic-tac-tic-tac-toe#1]
Hey!

When I try to "Join Team Github/Twitter", I got this error from `auth.firebase` : `{"code":"SERVICE_UNAVAILABLE","statusCode":410,"message":"SDK Update Required: See https://goo.gl/2cKQWm.","details":"SDK Update Required: https://goo.gl/2cKQWm. "}`

**Comment by jwngr** [comment]
Thanks for alerting me of this issue! I didn't realize I had never upgraded the Firebase SDK... I haven't touched this code in a while so I'm not sure how difficult the upgrade will be. I likely won't get to it for at least a few weekends. If you're interested in helping out, check out the [contribution instructions](https://github.com/jwngr/tic-tac-tic-tac-toe#contributing).

**Comment by HZooly** [comment]
Yes I can try to find some time to fix it 😸

**Comment by jwngr** [comment]
This has been fixed. I rewrote the web app in React and upgraded Firebase to the latest version.
